# Generated by Django 3.0.5 on 2020-04-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0002_auto_20200425_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='moderators',
        ),
        migrations.RemoveField(
            model_name='meetingseries',
            name='moderators',
        ),
    ]
