# Generated by Django 3.0.5 on 2020-04-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0004_invitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
