# Generated by Django 3.0.5 on 2020-04-26 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minutes.auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
