/* tslint:disable */
/* eslint-disable */
/**
 * Minutes API V1
 * django-minutes API specifications
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AnonymousVote,
    AnonymousVoteFromJSON,
    AnonymousVoteFromJSONTyped,
    AnonymousVoteToJSON,
} from './';

/**
 * 
 * @export
 * @interface AnonymousVoteResponse
 */
export interface AnonymousVoteResponse {
    /**
     * 
     * @type {number}
     * @memberof AnonymousVoteResponse
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof AnonymousVoteResponse
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AnonymousVoteResponse
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<AnonymousVote>}
     * @memberof AnonymousVoteResponse
     */
    results?: Array<AnonymousVote>;
}

export function AnonymousVoteResponseFromJSON(json: any): AnonymousVoteResponse {
    return AnonymousVoteResponseFromJSONTyped(json, false);
}

export function AnonymousVoteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnonymousVoteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(AnonymousVoteFromJSON)),
    };
}

export function AnonymousVoteResponseToJSON(value?: AnonymousVoteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(AnonymousVoteToJSON)),
    };
}


