/* tslint:disable */
/* eslint-disable */
/**
 * Minutes API V1
 * django-minutes API specifications
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnonymousVote
 */
export interface AnonymousVote {
    /**
     * 
     * @type {number}
     * @memberof AnonymousVote
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof AnonymousVote
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof AnonymousVote
     */
    voteClass: number;
    /**
     * 
     * @type {number}
     * @memberof AnonymousVote
     */
    decision: number;
}

export function AnonymousVoteFromJSON(json: any): AnonymousVote {
    return AnonymousVoteFromJSONTyped(json, false);
}

export function AnonymousVoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnonymousVote {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'amount': json['amount'],
        'voteClass': json['vote_class'],
        'decision': json['decision'],
    };
}

export function AnonymousVoteToJSON(value?: AnonymousVote | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'vote_class': value.voteClass,
        'decision': value.decision,
    };
}


