/* tslint:disable */
/* eslint-disable */
/**
 * Minutes API V1
 * django-minutes API specifications
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Decision,
    DecisionFromJSON,
    DecisionFromJSONTyped,
    DecisionToJSON,
} from './';

/**
 * 
 * @export
 * @interface DecisionResponse
 */
export interface DecisionResponse {
    /**
     * 
     * @type {number}
     * @memberof DecisionResponse
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof DecisionResponse
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DecisionResponse
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Decision>}
     * @memberof DecisionResponse
     */
    results?: Array<Decision>;
}

export function DecisionResponseFromJSON(json: any): DecisionResponse {
    return DecisionResponseFromJSONTyped(json, false);
}

export function DecisionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecisionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(DecisionFromJSON)),
    };
}

export function DecisionResponseToJSON(value?: DecisionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(DecisionToJSON)),
    };
}


