/* tslint:disable */
/* eslint-disable */
/**
 * Minutes API V1
 * django-minutes API specifications
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AgendaItem,
    AgendaItemFromJSON,
    AgendaItemFromJSONTyped,
    AgendaItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListAgendaItemsResponse
 */
export interface ListAgendaItemsResponse {
    /**
     * 
     * @type {number}
     * @memberof ListAgendaItemsResponse
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof ListAgendaItemsResponse
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListAgendaItemsResponse
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<AgendaItem>}
     * @memberof ListAgendaItemsResponse
     */
    results?: Array<AgendaItem>;
}

export function ListAgendaItemsResponseFromJSON(json: any): ListAgendaItemsResponse {
    return ListAgendaItemsResponseFromJSONTyped(json, false);
}

export function ListAgendaItemsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAgendaItemsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(AgendaItemFromJSON)),
    };
}

export function ListAgendaItemsResponseToJSON(value?: ListAgendaItemsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(AgendaItemToJSON)),
    };
}


