/* tslint:disable */
/* eslint-disable */
/**
 * Minutes API V1
 * django-minutes API specifications
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    VoteChoice,
    VoteChoiceFromJSON,
    VoteChoiceFromJSONTyped,
    VoteChoiceToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListVoteChoicesResponse
 */
export interface ListVoteChoicesResponse {
    /**
     * 
     * @type {number}
     * @memberof ListVoteChoicesResponse
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof ListVoteChoicesResponse
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListVoteChoicesResponse
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<VoteChoice>}
     * @memberof ListVoteChoicesResponse
     */
    results?: Array<VoteChoice>;
}

export function ListVoteChoicesResponseFromJSON(json: any): ListVoteChoicesResponse {
    return ListVoteChoicesResponseFromJSONTyped(json, false);
}

export function ListVoteChoicesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListVoteChoicesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(VoteChoiceFromJSON)),
    };
}

export function ListVoteChoicesResponseToJSON(value?: ListVoteChoicesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(VoteChoiceToJSON)),
    };
}


