/* tslint:disable */
/* eslint-disable */
/**
 * Minutes API V1
 * django-minutes API specifications
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeetingSeries
 */
export interface MeetingSeries {
    /**
     * 
     * @type {number}
     * @memberof MeetingSeries
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof MeetingSeries
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MeetingSeries
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MeetingSeries
     */
    readonly owners?: Array<string>;
}

export function MeetingSeriesFromJSON(json: any): MeetingSeries {
    return MeetingSeriesFromJSONTyped(json, false);
}

export function MeetingSeriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeetingSeries {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'owners': !exists(json, 'owners') ? undefined : json['owners'],
    };
}

export function MeetingSeriesToJSON(value?: MeetingSeries | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
    };
}


