/* tslint:disable */
/* eslint-disable */
/**
 * Minutes API V1
 * django-minutes API specifications
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Meeting
 */
export interface Meeting {
    /**
     * 
     * @type {number}
     * @memberof Meeting
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof Meeting
     */
    series: number;
    /**
     * 
     * @type {string}
     * @memberof Meeting
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof Meeting
     */
    date: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof Meeting
     */
    readonly owners?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Meeting
     */
    readonly participants?: Array<string>;
}

export function MeetingFromJSON(json: any): Meeting {
    return MeetingFromJSONTyped(json, false);
}

export function MeetingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Meeting {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'series': json['series'],
        'name': json['name'],
        'date': (new Date(json['date'])),
        'owners': !exists(json, 'owners') ? undefined : json['owners'],
        'participants': !exists(json, 'participants') ? undefined : json['participants'],
    };
}

export function MeetingToJSON(value?: Meeting | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'series': value.series,
        'name': value.name,
        'date': (value.date.toISOString()),
    };
}


