/* tslint:disable */
/* eslint-disable */
/**
 * Minutes API V1
 * django-minutes API specifications
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RollCallVote
 */
export interface RollCallVote {
    /**
     * 
     * @type {number}
     * @memberof RollCallVote
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof RollCallVote
     */
    voteClass: number;
    /**
     * 
     * @type {number}
     * @memberof RollCallVote
     */
    decision: number;
    /**
     * 
     * @type {number}
     * @memberof RollCallVote
     */
    user: number;
}

export function RollCallVoteFromJSON(json: any): RollCallVote {
    return RollCallVoteFromJSONTyped(json, false);
}

export function RollCallVoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): RollCallVote {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'voteClass': json['vote_class'],
        'decision': json['decision'],
        'user': json['user'],
    };
}

export function RollCallVoteToJSON(value?: RollCallVote | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'vote_class': value.voteClass,
        'decision': value.decision,
        'user': value.user,
    };
}


