/* tslint:disable */
/* eslint-disable */
/**
 * Minutes API V1
 * django-minutes API specifications
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SubItem,
    SubItemFromJSON,
    SubItemFromJSONTyped,
    SubItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface SubItemResponse
 */
export interface SubItemResponse {
    /**
     * 
     * @type {number}
     * @memberof SubItemResponse
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof SubItemResponse
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubItemResponse
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<SubItem>}
     * @memberof SubItemResponse
     */
    results?: Array<SubItem>;
}

export function SubItemResponseFromJSON(json: any): SubItemResponse {
    return SubItemResponseFromJSONTyped(json, false);
}

export function SubItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubItemResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(SubItemFromJSON)),
    };
}

export function SubItemResponseToJSON(value?: SubItemResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(SubItemToJSON)),
    };
}


