/* tslint:disable */
/* eslint-disable */
/**
 * Minutes API V1
 * django-minutes API specifications
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubItem
 */
export interface SubItem {
    /**
     * 
     * @type {number}
     * @memberof SubItem
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof SubItem
     */
    agendaItem: number;
    /**
     * 
     * @type {string}
     * @memberof SubItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SubItem
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SubItem
     */
    readonly mentions?: Array<string>;
}

export function SubItemFromJSON(json: any): SubItem {
    return SubItemFromJSONTyped(json, false);
}

export function SubItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'agendaItem': json['agenda_item'],
        'name': json['name'],
        'description': json['description'],
        'mentions': !exists(json, 'mentions') ? undefined : json['mentions'],
    };
}

export function SubItemToJSON(value?: SubItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'agenda_item': value.agendaItem,
        'name': value.name,
        'description': value.description,
    };
}


