/* tslint:disable */
/* eslint-disable */
/**
 * Minutes API V1
 * django-minutes API specifications
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenRefresh
 */
export interface TokenRefresh {
    /**
     * 
     * @type {string}
     * @memberof TokenRefresh
     */
    readonly authTokenKey?: string;
    /**
     * 
     * @type {Date}
     * @memberof TokenRefresh
     */
    readonly authTokenExpires?: Date;
    /**
     * 
     * @type {string}
     * @memberof TokenRefresh
     */
    readonly refreshTokenKey?: string;
    /**
     * 
     * @type {Date}
     * @memberof TokenRefresh
     */
    readonly refreshTokenExpires?: Date;
    /**
     * 
     * @type {string}
     * @memberof TokenRefresh
     */
    refreshToken: string;
}

export function TokenRefreshFromJSON(json: any): TokenRefresh {
    return TokenRefreshFromJSONTyped(json, false);
}

export function TokenRefreshFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenRefresh {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authTokenKey': !exists(json, 'auth_token_key') ? undefined : json['auth_token_key'],
        'authTokenExpires': !exists(json, 'auth_token_expires') ? undefined : (new Date(json['auth_token_expires'])),
        'refreshTokenKey': !exists(json, 'refresh_token_key') ? undefined : json['refresh_token_key'],
        'refreshTokenExpires': !exists(json, 'refresh_token_expires') ? undefined : (new Date(json['refresh_token_expires'])),
        'refreshToken': json['refresh_token'],
    };
}

export function TokenRefreshToJSON(value?: TokenRefresh | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'refresh_token': value.refreshToken,
    };
}


