/* tslint:disable */
/* eslint-disable */
/**
 * Minutes API V1
 * django-minutes API specifications
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenUserCredentials
 */
export interface TokenUserCredentials {
    /**
     * 
     * @type {string}
     * @memberof TokenUserCredentials
     */
    readonly authTokenKey?: string;
    /**
     * 
     * @type {Date}
     * @memberof TokenUserCredentials
     */
    readonly authTokenExpires?: Date;
    /**
     * 
     * @type {string}
     * @memberof TokenUserCredentials
     */
    readonly refreshTokenKey?: string;
    /**
     * 
     * @type {Date}
     * @memberof TokenUserCredentials
     */
    readonly refreshTokenExpires?: Date;
    /**
     * 
     * @type {string}
     * @memberof TokenUserCredentials
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof TokenUserCredentials
     */
    password: string;
}

export function TokenUserCredentialsFromJSON(json: any): TokenUserCredentials {
    return TokenUserCredentialsFromJSONTyped(json, false);
}

export function TokenUserCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenUserCredentials {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authTokenKey': !exists(json, 'auth_token_key') ? undefined : json['auth_token_key'],
        'authTokenExpires': !exists(json, 'auth_token_expires') ? undefined : (new Date(json['auth_token_expires'])),
        'refreshTokenKey': !exists(json, 'refresh_token_key') ? undefined : json['refresh_token_key'],
        'refreshTokenExpires': !exists(json, 'refresh_token_expires') ? undefined : (new Date(json['refresh_token_expires'])),
        'username': json['username'],
        'password': json['password'],
    };
}

export function TokenUserCredentialsToJSON(value?: TokenUserCredentials | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
    };
}


